package logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.List;

import example.Number;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;

public class JvmProberTest {
    @Test public void testJvmProber() throws InterruptedException {
       Number t1 = new Number(1);
       t1.doubleIt();
       t1.subtract(1);
       // SparkConf conf = new SparkConf();
       // conf = conf.setMaster("local[2]");
       // conf = conf.setAppName("LibraryTest");
       // JavaSparkContext sc = new JavaSparkContext(conf);
       // List<Integer> data = Arrays.asList(1,2,3,4,5,6,7);
       // sc.parallelize(data).count();
       // sc.stop();
    }
}
